language: python

install:
  - sudo apt-get update
  - ./.travis_miniconda.sh
  - PATH="$HOME/miniconda/bin:$PATH"
  - conda env create -f environment.yml
  - source activate trempy

script:
  - py.test --cov

after_success:
  - codecov
