language: python
python:
  - 3.7-dev
  - 3.6

bundler_args: --retry 3

install:
  - travis_retry travis_wait pip install -r requirements.txt
  - pip install codecov
  - pip install pytest-cov

script:
  - travis_wait pytest --cov

after_success:
  - codecov
