language: python

install:
  - sudo apt-get update
  - ./.travis_miniconda.sh
  - PATH="$HOME/miniconda/bin:$PATH"
  - conda env create -f environment.yml
  - source activate copulpy

script:
  - py.test
